### PR TITLE
Improvement/79 memory performance, fixing memory leaks

### LINKED ISSUE #79: Memory performance, fixing memory leaks

### PR DESCRIPTION
**Pull request by dmakarevich**

### CODE REVIEW

File: PhotoMap/Features/MapPhoto/Controllers/MapPhotoViewController.swift [hunk 1]
```diff
@@ -51,90 +66,96 @@ class MapPhotoViewController: BaseViewController {
...
+            .store(in: &cancellables)
 
         doneButton.tapPublisher
             .map { [weak self] _ in self?.descriptionTextView.text ?? "" }
-            .subscribe(viewModel.doneButtonSubject)
-            .store(in: cancelBag)
+            .sink(receiveValue: { [weak self] text in
+                    self?.view.endEditing(true)
+                    viewModel.doneButtonSubject.send(text) })
+//            .subscribe(viewModel.doneButtonSubject)
```
Comment (atereshkov) [inline PhotoMap/Features/MapPhoto/Controllers/MapPhotoViewController.swift:122]: Subscribe produces leak even when using Set of AnyCancellable?

**Review by atereshkov — CHANGES_REQUESTED** [review]
